spring.application.name=backend

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/research_journal_db
spring.datasource.username=postgres
spring.datasource.password=2005

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080

logging.level.org.springframework.security=DEBUG

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE